# Generated by Django 3.0.1 on 2019-12-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
