# Generated by Django 3.0.1 on 2020-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(max_length=120),
        ),
    ]
